Float functions
IanBriggs/megalibm pull request #15
Opened 2023-04-04 14:02 UTC by yashladd

2023-04-04 17:36 UTC, IanBriggs requested changes
Overall looks good. 👍 

Please move the substitute float operation code to its own file before merge.

2023-04-04 17:36 UTC, IanBriggs commented on src/fpcore/ast_methods/substitute.py
Please move this to it's own file in `ast_methods`

2023-04-04 17:36 UTC, IanBriggs commented on src/fpcore/ast_methods/to_libm_c.py
> +        return _CONST_MAPPING[self.source] if not is_float else f"(float) {_CONST_MAPPING[self.source]}"
Good solution to this issue!

2023-04-04 17:36 UTC, IanBriggs commented on src/lambdas/cody_waite.py
> +                new_cases[k] = body.replace_lambda(search, replace)
Thanks for fixing my mistake

2023-04-05 00:26 UTC, yashladd commented on src/fpcore/ast_methods/substitute.py
Done

2023-04-05 00:26 UTC, yashladd commented on src/fpcore/ast_methods/to_libm_c.py
> +        return _CONST_MAPPING[self.source] if not is_float else f"(float) {_CONST_MAPPING[self.source]}"
Thanks!

2023-04-05 00:27 UTC, yashladd commented
Thank you! merging

2023-04-05 00:27 UTC, merged